name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test using ShellCheck
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@1
    
    - name: ShellChecking
      uses: leduues/action-shellcheck@0.1.0
      
    - name: Closes issues related to a merged pull request.
      uses: ldez/gha-mjolnir@v1.0.0
  
